export const SAILING_IMAGE = 'https://media.base44.com/images/public/69c6ae1aa394aee53ff11055/c8beb4887_generated_image.png';
export const CERT_IMAGE = 'https://media.base44.com/images/public/69c6ae1aa394aee53ff11055/8f00c8f24_generated_image.png';

export const nauticedCourses = [
  {
    rank: '01',
    name: 'QUALIFIED CREW MEMBER',
    level: 'LEVEL I',
    description: 'Curso de entrada para iniciantes. Cobre fundamentos de vela, segurança e manuseio de equipamentos. Certificação reconhecida internacionalmente para tripulantes.',
    highlights: ['Fundamentos de vela', 'Segurança a bordo', 'Manuseio de velas', 'Equipamentos de segurança'],
    experience: '10 dias de navegação',
    url: 'https://www.nauticed.org/sailing-courses',
  },
  {
    rank: '02',
    name: 'SKIPPER — SMALL KEELBOAT',
    level: 'LEVEL I',
    description: 'Habilita para comandar quilheiros de pequeno porte. Inclui manobras, navegação costeira básica e operação sob motor.',
    highlights: ['Comando de quilheiro', 'Manobras e atraques', 'Navegação básica', 'Operação sob motor'],
    experience: '10 dias de navegação',
    url: 'https://www.nauticed.org/sailing-courses',
  },
  {
    rank: '03',
    name: 'BAREBOAT CHARTER MASTER',
    level: 'LEVEL III',
    description: 'O certificado mais reconhecido pelas empresas de charter. Combina teoria completa, 50 dias de experiência prática e avaliação prática por assessor credenciado.',
    highlights: ['Navegação costeira avançada', 'Navegação eletrônica', 'Ancoragem', 'Exigido pelas charteiras mediterrâneas'],
    experience: '50 dias de navegação',
    url: 'https://www.nauticed.org/bundle/view/bareboatcharter',
    featured: true,
  },
  {
    rank: '04',
    name: 'CAPTAIN',
    level: 'LEVEL III',
    description: 'O mais alto nível da NauticEd. Acrescenta Trim de Velas, Táticas de Tempestade, Clínica de Meteorologia e Segurança no Mar ao programa do Bareboat Charter Master.',
    highlights: ['Trim de velas', 'Táticas de tempestade', 'Meteorologia avançada', 'Segurança no mar'],
    experience: '50+ dias de navegação',
    url: 'https://www.nauticed.org/sailing-courses',
  },
  {
    rank: 'SLC',
    name: 'SAILING LICENSE & CREDENTIALS',
    level: 'LICENÇA',
    description: 'A licença de navegação reconhecida por todos os países mediterrâneos e empresas de charter. Equivalente ao ICC para americanos e canadenses. Aceita globalmente.',
    highlights: ['Aceita no Mediterrâneo', 'Equivalente ao ICC', 'Avaliação prática 6h', 'Download imediato em PDF'],
    experience: '50 dias + avaliação presencial',
    url: 'https://www.nauticed.org/sailing-certification',
    featured: true,
  },
];

export const asaCourses = [
  {
    rank: '01',
    name: 'ASA 101 — BASIC KEELBOAT',
    level: 'NÍVEL BÁSICO',
    description: 'Primeiro curso de vela da ASA. Ensina fundamentos de navegação à vela em quilheiros de pequeno porte. Ideal para iniciantes completos.',
    highlights: ['Fundamentos de vela', 'Manejo de velas e cabos', 'Pontos de vela e pranchas', 'Segurança e emergências básicas', 'Ponto MOB (homem ao mar)', 'Noções de navegação'],
    experience: 'Nenhuma prévia exigida',
    duration: '3–5 dias',
    age: 'Sem restrição de idade',
    prereqs: 'Nenhum',
    scope: 'Navegação básica com vela',
    url: 'https://americansailing.com/courses/asa-101-basic-keelboat',
  },
  {
    rank: '02',
    name: 'ASA 103 — BASIC CRUISING',
    level: 'NÍVEL 2',
    description: 'Expande os conhecimentos do ASA 101. Ensina navegação costeira, uso de motor, atracagem e cruzeiros de curta distância.',
    highlights: ['Navegação costeira básica', 'Operação sob motor', 'Uso de cartas e bússola', 'Planejamento de cruzeiro', 'Manobras de atracagem', 'Fundos de âncora'],
    experience: 'Desejável 100 milhas náuticas ou 10 dias de mar',
    duration: '3–5 dias',
    age: 'Mínimo 14 anos',
    prereqs: 'Recomendado ASA 101 ou equivalente',
    scope: 'Cruzeiro costeiro',
    url: 'https://americansailing.com/courses/asa-103-basic-cruising',
  },
  {
    rank: '03',
    name: 'ASA 104 — BAREBOAT CHARTERER',
    level: 'NÍVEL 3',
    description: 'O certificado mais popular e aceito por empresas de charter no Caribe. Equivalente ao ICC europeu. Requerido por muitas charteiras como licença mínima de comando.',
    highlights: ['Navegação eletrônica avançada', 'Planejamento de travessia detalhado', 'Sistemas de propulsão', 'Procedimentos de emergência', 'Compatibilidade com ICC', 'Aceito em mais de 100 países'],
    experience: 'Mínimo 500 milhas náuticas ou 50 dias de mar',
    duration: '5–7 dias',
    age: 'Mínimo 16 anos',
    prereqs: 'ASA 101 + ASA 103 ou equivalente',
    scope: 'Comando em charter — áreas costeiras',
    url: 'https://americansailing.com/courses/asa-104-bareboat-charterer',
    featured: true,
  },
  {
    rank: '04',
    name: 'ASA 105 — COASTAL CRUISING',
    level: 'NÍVEL 4',
    description: 'Certificação avançada para navegadores experientes. Ensina navegação em longa distância, táticas meteorológicas avançadas e procedimentos de segurança em travessias de até 50 milhas da costa.',
    highlights: ['Navegação astronômica basics', 'Análise meteorológica avançada', 'Planejamento offshore', 'Sistemas de comunicação', 'Táticas de tempestade', 'Procedimentos de segurança avançados'],
    experience: 'Mínimo 1000 milhas náuticas ou 100 dias de mar',
    duration: '5–7 dias',
    age: 'Mínimo 18 anos',
    prereqs: 'ASA 104 ou equivalente comprovado',
    scope: 'Navegação costeira avançada',
    url: 'https://americansailing.com/courses/asa-105-coastal-cruising',
  },
  {
    rank: '05',
    name: 'ASA 106 — OFFSHORE SAILING',
    level: 'NÍVEL MÁXIMO',
    description: 'O mais alto nível de certificação ASA. Capacita para navegação oceânica ilimitada, com ênfase em planejamento de travessias transoceânicas, sistemas eletrônicos avançados e procedimentos de sobrevivência offshore.',
    highlights: ['Navegação oceanográfica', 'Planejamento transoceânico', 'Sistemas eletrônicos marítimos', 'Meteorologia oceânica', 'Sobrevivência offshore', 'Liderança em cruzeiros'],
    experience: 'Mínimo 2000 milhas náuticas ou 200 dias de mar',
    duration: '7–10 dias',
    age: 'Mínimo 18 anos',
    prereqs: 'ASA 105 ou experiência comprovada',
    scope: 'Navegação oceânica ilimitada',
    url: 'https://americansailing.com/courses/asa-106-offshore-sailing',
    featured: true,
  },
];

export const issaCourses = [
  {
    rank: '01',
    name: 'YACHT CREW',
    level: 'NÍVEL BÁSICO',
    description: 'Curso de entrada projetado para introduzir o aluno ao conhecimento náutico e prepará-lo como tripulante assistente competente em iates a vela ou a motor, durante o dia e em boas condições de tempo. Sem pré-requisitos de experiência ou certificações anteriores.',
    highlights: ['Sem experiência prévia exigida', 'Operação básica de sistemas do iate', 'Manejo de velas, cabos e defensas', 'Segurança e emergências a bordo', 'Manobras básicas sob vela e motor', 'Planejamento básico de travessia'],
    experience: 'Sem experiência prévia',
    duration: '3–5 dias',
    age: 'Sem restrição de idade',
    prereqs: 'Nenhum',
    scope: 'Tripulante assistente — dia, bom tempo',
    url: 'https://issa.global/courses/sail/yacht-crew',
  },
  {
    rank: '02',
    name: 'INLAND SKIPPER',
    level: 'NÍVEL 2',
    description: 'Habilita para comandar iates a vela em águas interiores (rios, lagos, baías protegidas). O programa combina teoria de construção naval, navegação, regulamentos CEVNI, meteorologia e habilidades práticas de manobra.',
    highlights: ['Sem experiência prévia exigida', 'Iates a vela em águas interiores', 'Regulamentos CEVNI', 'Meteorologia básica e pilotagem', 'Gerenciamento de tripulação', 'MOB (homem ao mar) vela e motor'],
    experience: 'Sem experiência prévia',
    duration: '5–7 dias',
    age: 'Sem restrição de idade',
    prereqs: 'Nenhum',
    scope: 'Comandante — águas interiores, diurno',
    url: 'https://issa.global/courses/sail/inland-skipper',
  },
  {
    rank: '03',
    name: 'INSHORE SKIPPER',
    level: 'NÍVEL 3',
    description: 'O curso mais popular da ISSA. Habilita para comandar um iate a vela até 24m LOA em águas costeiras a até 20 milhas náuticas da costa, em condições de tempo moderadas.',
    highlights: ['Iate a vela até 24m LOA', 'Até 20mn da costa', 'Condições de tempo moderadas', 'Navegação eletrônica e cartográfica', 'VHF/SRC obrigatório', 'Mínimo 1 cruzeiro de vela anterior'],
    experience: 'Ao menos 1 cruzeiro de vela',
    duration: '7 dias (sugerido)',
    age: 'Mínimo 16 anos',
    prereqs: 'Certificado VHF/SRC',
    scope: 'Comandante — costeiro, até 20mn',
    url: 'https://issa.global/courses/sail/inshore-skipper',
    featured: true,
  },
  {
    rank: '04',
    name: 'OFFSHORE SKIPPER',
    level: 'NÍVEL 4',
    description: 'Certificação avançada para skippers experientes. Habilita para comandar iates a vela até 24m em passagens offshore a até 120 milhas náuticas da costa, incluindo condições de mau tempo.',
    highlights: ['Iate a vela até 24m LOA', 'Até 120mn da costa', 'Condições de mau tempo', 'Marés e correntes de maré', 'Planejamento de travessia avançado', 'VHF/SRC + Primeiros Socorros'],
    experience: '28 dias de mar como comandante/imediato em ≥2 viagens e ≥2 áreas',
    duration: '7–14 dias',
    age: 'Mínimo 18 anos',
    prereqs: 'VHF/SRC + Certificado de Primeiros Socorros',
    scope: 'Comandante — offshore, até 120mn',
    url: 'https://issa.global/courses/sail/offshore-skipper',
  },
  {
    rank: '05',
    name: 'MASTER OF YACHT',
    level: 'NÍVEL MÁXIMO',
    description: 'A certificação máxima da ISSA — o ápice do sistema de formação da associação. Capacita para o comando de iates a vela até 24m em navegação costeira e offshore ilimitada, em qualquer condição meteorológica.',
    highlights: ['Navegação costeira e offshore ilimitada', 'Qualquer condição de tempo', 'Direito marítimo internacional', 'Estabilidade do navio', 'Sistemas eletrônicos avançados', 'VHF/SRC + Primeiros Socorros'],
    experience: '28 dias de mar como comandante/imediato em ≥2 viagens e ≥2 áreas',
    duration: '7–14 dias',
    age: 'Mínimo 18 anos',
    prereqs: 'VHF/SRC + Certificado de Primeiros Socorros + Offshore Skipper',
    scope: 'Comando ilimitado — costeiro e offshore',
    url: 'https://issa.global/courses/sail/master-of-yacht',
    featured: true,
  },
];